API:
  LARGE_API_KEY: dummy-key
  LARGE_MODEL: phi4:latest
  LARGE_BASE_URL: http://localhost:11434/v1
  LARGE_MODE: api
  SMALL_MODEL: phi4:latest
  SMALL_BASE_URL: http://localhost:11434/v1
  SMALL_API_KEY: dummy-key
  SMALL_MODE: api

HUGGINGFACE:
  HUB_PATH: yourusername/your-path-here
  PRIVATE: False
  PUSH_TO_HUB: False

PATH:
  INPUT: "./raw_txt_input"
  OUTPUT: "./output"
  DEFAULT_PROMPTS: "./prompts"
  PROMPTS: "./kiran_university_assistant/prompts"

SKIP:
  ANSWER_RELEVANCY_CHECK: False
  FILTER_CHUNKS: False
  QUESTION_CHECK: False
  CONVERSATION_GENERATION: False
  REPAIR_QA_TUPLES: False

SYSTEM:
  CHUNK_SIZE: 1500
  USE_FILENAMES: True
  COMPLETION_MODE: False
  CONCURRENCY_LIMIT: 1
  DOUBLE_CHECK_COUNTER: 1
  DO_NOT_USE_SYSTEM_PROMPTS: False
  FINAL_ASSISTANT_PROMPTS_NO_RAG: [
    'Hello! I am Kiran, an AI assistant from Tampere University, dedicated to providing you with accurate and insightful assistance. My goal is to help you understand concepts, summarize lectures, and answer questions effectively.'
  ]
  FINAL_ASSISTANT_PROMPTS_RAG: [
    'Hello! I am Kiran, an AI assistant from Tampere University, dedicated to providing you with accurate and insightful assistance. My goal is to help you understand concepts, summarize lectures, and answer questions effectively. I have some relevant information that might help:
    
    {data}'
  ]
  MODE: api
  STOP: true
  SUBSET_SIZE: 10
  USE_SUBSET: true # Set to false when you're ready to process all data

PHASE:
  WORK_IN_PHASES: False
  PHASE_INDEX: 0